apiVersion: apps/v1
kind: Deployment
metadata: 
    name: frontend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: student-app-frontend
          image: r25gajengi/student-app-frontend:v2
          ports:
            - containerPort: 80
