apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=        # base64 for "admin"
  password: UmFqZXNoMTIzNA== # base64 for "Rajesh1234"
  



# cm9vdA==  # root
# UmFqZXNoMTIzNA==  # Rajesh1234
# bmlsZXNoMTIzNA==  # nilesh1234